# Generated by Django 4.1.2 on 2022-10-06 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('height', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winter', models.CharField(default='', max_length=10)),
                ('summer', models.CharField(default='', max_length=10)),
                ('autumn', models.CharField(default='', max_length=10)),
                ('spring', models.CharField(default='', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='PerevalAreas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_parent', models.IntegerField(null=True)),
                ('title', models.TextField(null=True)),
            ],
            options={
                'db_table': 'pereval_areas',
            },
        ),
        migrations.CreateModel(
            name='PerevalImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=20)),
                ('img', models.BinaryField()),
            ],
            options={
                'db_table': 'pereval_images',
            },
        ),
        migrations.CreateModel(
            name='SprActivitiesTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(null=True)),
            ],
            options={
                'db_table': 'spr_activities_types',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('fam', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('otc', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PerevalAdded',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateField(auto_now_add=True)),
                ('beauty_title', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255, unique=True)),
                ('other_title', models.CharField(max_length=255)),
                ('connect', models.TextField(default='')),
                ('add_time', models.TimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('new', 'Новая заявка на модерацию'), ('pen', 'Модерируется'), ('acc', 'Модерация прошла успешно'), ('rej', 'Модерация прошла, информация не принята')], default='new', max_length=3)),
                ('coord_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coords_id', to='perevals_app.coord')),
                ('images_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images_id', to='perevals_app.perevalimages')),
                ('level_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='level_id', to='perevals_app.level')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_id', to='perevals_app.user')),
            ],
            options={
                'db_table': 'pereval_added',
            },
        ),
    ]
